package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Advertise generated by hbm2java
 */
public class Advertise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7602084818359465627L;
	private Integer id;
	private String img;
	private String url;
	private String alt;
	private String notes;
	private Date date;
	private Integer clickedCount;

	public Advertise() {
	}

	public Advertise(Date date) {
		this.date = date;
	}

	public Advertise(String img, String url, String alt, String notes, Date date, Integer clickedCount) {
		this.img = img;
		this.url = url;
		this.alt = alt;
		this.notes = notes;
		this.date = date;
		this.clickedCount = clickedCount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAlt() {
		return this.alt;
	}

	public void setAlt(String alt) {
		this.alt = alt;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getClickedCount() {
		return this.clickedCount;
	}

	public void setClickedCount(Integer clickedCount) {
		this.clickedCount = clickedCount;
	}

}
