package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

import java.util.List;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -685125355486956382L;
	private Integer id;
	private String name;
	private String description;
	private String bigImg;
	private String style;
	private String smallImg;
	private List<Subcategory> children;

	
	public Category() {
	}

	

	public Category(Integer id, String name, String description, String bigImg, String style, String smallImg,
			Subcategory children) {
		super();
		this.id = id;
		this.name = name;
		this.description = description;
		this.bigImg = bigImg;
		this.style = style;
		this.smallImg = smallImg;
	}



	public void setChildren(List<Subcategory> children) {
		this.children = children;
	}

	public List<Subcategory> getChildren() {
		return children;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBigImg() {
		return this.bigImg;
	}

	public void setBigImg(String bigImg) {
		this.bigImg = bigImg;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getSmallImg() {
		return this.smallImg;
	}

	public void setSmallImg(String smallImg) {
		this.smallImg = smallImg;
	}

}
