package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

/**
 * Counter generated by hbm2java
 */
public class Counter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4400450157988622379L;
	private Integer id;
	private Integer digit;
	private Integer count;

	public Counter() {
	}

	public Counter(Integer digit, Integer count) {
		this.digit = digit;
		this.count = count;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDigit() {
		return this.digit;
	}

	public void setDigit(Integer digit) {
		this.digit = digit;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
