package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

/**
 * Nextorderid generated by hbm2java
 */
public class Nextorderid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6400154070109706587L;
	private Integer id;
	private Integer nextId;

	public Nextorderid() {
	}

	public Nextorderid(Integer nextId) {
		this.nextId = nextId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNextId() {
		return this.nextId;
	}

	public void setNextId(Integer nextId) {
		this.nextId = nextId;
	}

}
