package com.csxh.eshop.model;
// Generated 2015-11-30 10:41:02 by Hibernate Tools 4.3.1.Final

/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7894491965344918812L;
	private Integer id;
	private Integer orderId;
	private String productId;
	private String productName;
	private Double unitPrice;
	private Integer quantity;
	private Float unitWeight;

	public Orderdetails() {
	}

	public Orderdetails(Integer orderId, String productId, String productName, Double unitPrice, Integer quantity,
			Float unitWeight) {
		this.orderId = orderId;
		this.productId = productId;
		this.productName = productName;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.unitWeight = unitWeight;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Float getUnitWeight() {
		return this.unitWeight;
	}

	public void setUnitWeight(Float unitWeight) {
		this.unitWeight = unitWeight;
	}

}
