package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

/**
 * Paymethod generated by hbm2java
 */
public class Paymethod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8854125249928413226L;
	private Integer id;
	private String name;

	public Paymethod() {
	}

	public Paymethod(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
