package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -257749360898042071L;
	private String id;
	private String name;
	private Integer categoryId;
	private Integer subCategoryId;
	private String supplier;
	private String author;
	private String description;
	private Double price;
	private Double listPrice;
	private Boolean hotDeal;
	private Date pubDate;
	private Date addDate;
	private Boolean commend;
	private String smallImg;
	private String bigImg;
	private Integer stock;
	private Integer sell;
	private Integer visits;
	private Float unitWeight;
	
	private Category category;
	private Subcategory subCategory;

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Subcategory getSubCategory() {
		return subCategory;
	}

	public void setSubCategory(Subcategory subCategory) {
		this.subCategory = subCategory;
	}

	public Product() {
	}

	public Product(String id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	public Product(String id, String name, Integer categoryId, Integer subCategoryId, String supplier, String author,
			String description, Double price, Double listPrice, Boolean hotDeal, Date pubDate, Date addDate, Boolean commend,
			String smallImg, String bigImg, Integer stock, Integer sell, Integer visits, Float unitWeight) {
		this.id = id;
		this.name = name;
		this.categoryId = categoryId;
		this.subCategoryId = subCategoryId;
		this.supplier = supplier;
		this.author = author;
		this.description = description;
		this.price = price;
		this.listPrice = listPrice;
		this.hotDeal = hotDeal;
		this.pubDate = pubDate;
		this.addDate = addDate;
		this.commend = commend;
		this.smallImg = smallImg;
		this.bigImg = bigImg;
		this.stock = stock;
		this.sell = sell;
		this.visits = visits;
		this.unitWeight = unitWeight;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(Integer subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(Double listPrice) {
		this.listPrice = listPrice;
	}

	public Boolean getHotDeal() {
		return this.hotDeal;
	}

	public void setHotDeal(Boolean hotDeal) {
		this.hotDeal = hotDeal;
	}

	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public Boolean getCommend() {
		return this.commend;
	}

	public void setCommend(Boolean commend) {
		this.commend = commend;
	}

	public String getSmallImg() {
		return this.smallImg;
	}

	public void setSmallImg(String smallImg) {
		this.smallImg = smallImg;
	}

	public String getBigImg() {
		return this.bigImg;
	}

	public void setBigImg(String bigImg) {
		this.bigImg = bigImg;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Integer getSell() {
		return this.sell;
	}

	public void setSell(Integer sell) {
		this.sell = sell;
	}

	public Integer getVisits() {
		return this.visits;
	}

	public void setVisits(Integer visits) {
		this.visits = visits;
	}

	public Float getUnitWeight() {
		return this.unitWeight;
	}

	public void setUnitWeight(Float unitWeight) {
		this.unitWeight = unitWeight;
	}

	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", author=" + author + ", description=" + description
				+ ", smallImg=" + smallImg + "]";
	}

	
}
