package com.csxh.eshop.model;
// Generated 2015-11-19 16:57:11 by Hibernate Tools 4.3.1.Final

/**
 * Rating generated by hbm2java
 */
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1315447146561839017L;
	private Integer id;
	private String productId;
	private Integer rateLevel;

	public Rating() {
	}

	public Rating(String productId, Integer rateLevel) {
		this.productId = productId;
		this.rateLevel = rateLevel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Integer getRateLevel() {
		return this.rateLevel;
	}

	public void setRateLevel(Integer rateLevel) {
		this.rateLevel = rateLevel;
	}

}
